# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9df475de3d0b8a3d6e30a9f6cfd1875ecbe2d4734674a76ada08b6cdcd18986d925917cc89ef7d566779c6307cd1175180d900fdd08a5f2a73c7f28abacdec0

test:
  secret_key_base: 5034f3c8ffe94f84ca6fd73af06d392ebe3e99fe41233c6df89e93977b8cb3d319fb2c44724e850990c098d95289a5f9f7da52be4ca6c28f8d559baa72cc1745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
